name: Run KS Panel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # ✅ Install ALL deps (including dev)
      - name: Install dependencies
        run: npm install

      - name: Run Prisma db push
        run: npm run migrate:dev

      # ✅ Now TypeScript will work
      - name: Build project
        run: npm run build

      - name: Create user
        run: npm run create:user kshosting kshosting@ksmail.com kshosting@55

      - name: Install cloudflared
        run: |
          curl -L -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Start Cloudflare Tunnel
        run: |
          sudo cloudflared service install eyJhIjoiZTJkZjY3MDI5ZWZlZTBmY2JhM2ExMjNjN2VmNTcxNTAiLCJ0IjoiMGQ2Yzk5YjQtMGUzZC00NzEyLWFmNDctNzM0MGU5YTEyOGE3IiwicyI6IlkyVTNOelV5WmpBdFl6SmpOeTAwTjJZMExUbGpNMk10T0dJelltRmtOREk1T1dOaCJ9

      - name: Start KS Panel
        run: npm run start

      
